=== Vladeks/EPAMtask/task13_XML/src/resource/diamondfund.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gem" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="preciousness" type="precious"/>
                            <xs:element name="origin" type="xs:string"/>
                            <xs:element name="visualParameters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="color" type="color" minOccurs="0"/>
                                        <xs:element name="transparency" type="percentage" minOccurs="0"/>
                                        <xs:element name="diamondCut" type="cutCount" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="value" type="karat"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

<!--types-->

    <xs:simpleType name="percentage" >
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cutCount">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="4"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <!--<xs:simpleType name="karat">-->
        <!--<xs:restriction base="xs:string">-->
            <!--<xs:pattern value="[1-9][0-9]?K"/>-->
        <!--</xs:restriction>-->
    <!--</xs:simpleType>-->

    <xs:simpleType name="karat">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="24"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="precious" final="restriction" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="precious" />
            <xs:enumeration value="semiprecious" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color" final="restriction" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="colorless" />
            <xs:enumeration value="white" />
            <xs:enumeration value="black" />
            <xs:enumeration value="pink" />
            <xs:enumeration value="red" />
            <xs:enumeration value="blue" />
            <xs:enumeration value="green" />
            <xs:enumeration value="yellow" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Vladeks/EPAMtask/task13_XML/src/resource/diamondfund.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems name="MyFund"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="diamondfund.xsd">
    <gem>
        <name>MyGem</name>
        <preciousness>semiprecious</preciousness>
        <origin>Zimbabwe</origin>
        <visualParameters>
            <color>colorless</color>
            <transparency>79</transparency>
            <diamondCut>15</diamondCut>
        </visualParameters>
        <value>1</value>
    </gem>
    <gem>
        <name>MyGem2</name>
        <preciousness>precious</preciousness>
        <origin>Zimbabwe</origin>
        <visualParameters>
            <color>white</color>
            <transparency>80</transparency>
            <diamondCut>14</diamondCut>
        </visualParameters>
        <value>24</value>
    </gem>
</gems>
